//auth

export const AUTH_LOGIN_STUDENT = "AUTH_LOGIN_STUDENT";
export const AUTH_LOGIN_STUDENT_SUCCESS = "AUTH_LOGIN_STUDENT_SUCCESS";
export const AUTH_LOGIN_STUDENT_FAILURE = "AUTH_LOGIN_STUDENT_FAILURE";

export const AUTH_LOGIN_TEACHER = "AUTH_LOGIN_TEACHER";
export const AUTH_LOGIN_TEACHER_SUCCESS = "AUTH_LOGIN_TEACHER_SUCCESS";
export const AUTH_LOGIN_TEACHER_FAILURE = "AUTH_LOGIN_TEACHER_FAILURE";

export const UPDATE_TEACHER_PROFILE = "UPDATE_TEACHER_PROFILE";
export const UPDATE_TEACHER_PROFILE_SUCCESS = "UPDATE_TEACHER_PROFILE_SUCCESS";
export const UPDATE_TEACHER_PROFILE_FAILURE = "UPDATE_TEACHER_PROFILE_FAILURE";

export const UPDATE_TEACHER_PROFILE_PASSWORD =
  "UPDATE_TEACHER_PROFILE_PASSWORD";
export const UPDATE_TEACHER_PROFILE_PASSWORD_SUCCESS =
  "UPDATE_TEACHER_PROFILE_PASSWORD_SUCCESS";
export const UPDATE_TEACHER_PROFILE_PASSWORD_FAILURE =
  "UPDATE_TEACHER_PROFILE_PASSWORD_FAILURE";

export const AUTH_USER_LOGOUT = "AUTH_USER_LOGOUT";
export const AUTH_USER_LOGOUT_SUCCESS = "AUTH_USER_LOGOUT_SUCCESS";
export const AUTH_USER_LOGOUT_FAILURE = "AUTH_USER_LOGOUT_FAILURE";

export const AUTH_FORGOT_PASSWORD = "AUTH_FORGOT_PASSWORD";
export const AUTH_FORGOT_PASSWORD_SUCCESS = "AUTH_FORGOT_PASSWORD_SUCCESS";
export const AUTH_FORGOT_PASSWORD_FAILURE = "AUTH_FORGOT_PASSWORD_FAILURE";

export const AUTH_TEACHER_SIGN_UP = "AUTH_TEACHER_SIGN_UP";
export const AUTH_TEACHER_SIGN_UP_SUCCESS = "AUTH_TEACHER_SIGN_UP_SUCCESS";
export const AUTH_TEACHER_SIGN_UP_FAILURE = "AUTH_TEACHER_SIGN_UP_FAILURE";

export const AUTH_GOOGLE_TEACHER_SIGN_UP = "AUTH_GOOGLE_TEACHER_SIGN_UP";
export const AUTH_GOOGLE_TEACHER_SIGN_UP_SUCCESS =
  "AUTH_GOOGLE_TEACHER_SIGN_UP_SUCCESS";
export const AUTH_GOOGLE_TEACHER_SIGN_UP_FAILURE =
  "AUTH_GOOGLE_TEACHER_SIGN_UP_FAILURE";

export const AUTH_RESET_PASSWORD = "AUTH_RESET_PASSWORD";
export const AUTH_RESET_PASSWORD_SUCCESS = "AUTH_RESET_PASSWORD_SUCCESS";
export const AUTH_RESET_PASSWORD_FAILURE = "AUTH_RESET_PASSWORD_FAILURE";

export const AUTH_MAIL_CONFIRM = "AUTH_MAIL_CONFIRM";
export const AUTH_MAIL_CONFIRM_SUCCESS = "AUTH_MAIL_CONFIRM_SUCCESS";
export const AUTH_MAIL_CONFIRM_FAILURE = "AUTH_MAIL_CONFIRM_FAILURE";

export const AUTH_RESEND_VERIFICATION_MAIL = "AUTH_RESEND_VERIFICATION_MAIL";
export const AUTH_RESEND_VERIFICATION_MAIL_SUCCESS =
  "AUTH_RESEND_VERIFICATION_MAIL_SUCCESS";
export const AUTH_RESEND_VERIFICATION_MAIL_FAILURE =
  "AUTH_RESEND_VERIFICATION_MAIL_FAILURE";

// all user

export const FETCH_ALL_USER_LIST = "FETCH_ALL_USER_LIST";
export const FETCH_ALL_USER_LIST_SUCCESS = "FETCH_ALL_USER_LIST_SUCCESS";
export const FETCH_ALL_USER_LIST_FAILURE = "FETCH_ALL_USER_LIST_FAILURE";

//fetch from google class room

export const FETCH_ALL_USER_LIST_FROM_GOOGLE_CLASSROOM =
  "FETCH_ALL_USER_LIST_FROM_GOOGLE_CLASSROOM";
export const FETCH_ALL_USER_LIST_FROM_GOOGLE_CLASSROOM_SUCCESS =
  "FETCH_ALL_USER_LIST_FROM_GOOGLE_CLASSROOM_SUCCESS";
export const FETCH_ALL_USER_LIST_FROM_GOOGLE_CLASSROOM_FAILURE =
  "FETCH_ALL_USER_LIST_FROM_GOOGLE_CLASSROOM_FAILURE";

export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";
export const FETCH_USER_DETAILS_FAILURE = "FETCH_USER_DETAILS_FAILURE";

export const DELETE_USER_DETAILS = "DELETE_USER_DETAILS";
export const DELETE_USER_DETAILS_SUCCESS = "DELETE_USER_DETAILS_SUCCESS";
export const DELETE_USER_DETAILS_FAILURE = "DELETE_USER_DETAILS_FAILURE";

//Add User
export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const FETCH_ALL_USER_WITH_CLASS_LIST = "FETCH_ALL_USER_WITH_CLASS_LIST";
export const FETCH_ALL_USER_WITH_CLASS_LIST_SUCCESS =
  "FETCH_ALL_USER_WITH_CLASS_LIST_SUCCESS";
export const FETCH_ALL_USER_WITH_CLASS_LIST_FAILURE =
  "FETCH_ALL_USER_WITH_CLASS_LIST_FAILURE";

//Add Users
export const ADD_USERS = "ADD_USERS";
export const ADD_USERS_SUCCESS = "ADD_USERS_SUCCESS";
export const ADD_USERS_FAILURE = "ADD_USERS_FAILURE";
//Edit Student
export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";

export const EDIT_MULTIPLE_USER = "EDIT_MULTIPLE_USER";
export const EDIT_MULTIPLE_USER_SUCCESS = "EDIT_MULTIPLE_USER_SUCCESS";
export const EDIT_MULTIPLE_USER_FAILURE = "EDIT_MULTIPLE_USER_FAILURE";

//Delete User
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const DELETE_MULTIPLE_USER = "DELETE_MULTIPLE_USER";
export const DELETE_MULTIPLE_USER_SUCCESS = "DELETE_MULTIPLE_USER_SUCCESS";
export const DELETE_MULTIPLE_USER_FAILURE = "DELETE_MULTIPLE_USER_FAILURE";

//UPDATE USER LEVEL ID

export const UPDATE_USER_LEVEL_ID = "UPDATE_USER_LEVEL_ID";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";

//UPDATE USER LEVEL LIFTER COUNT

export const UPDATE_USER_LEVEL_LIFTER_COUNT = "UPDATE_USER_LEVEL_LIFTER_COUNT";

// notifications
export const NOTIFICATIONS_ENQUEUE_SNACKBAR = "NOTIFICATIONS_ENQUEUE_SNACKBAR";
export const NOTIFICATIONS_CLOSE_SNACKBAR = "NOTIFICATIONS_CLOSE_SNACKBAR";
export const NOTIFICATIONS_REMOVE_SNACKBAR = "NOTIFICATIONS_REMOVE_SNACKBAR";

export const FETCH_ALL_NOTIFICATIONS_LIST = "FETCH_ALL_NOTIFICATIONS_LIST";
export const FETCH_ALL_NOTIFICATIONS_LIST_SUCCESS =
  "FETCH_ALL_NOTIFICATIONS_LIST_SUCCESS";
export const FETCH_ALL_NOTIFICATIONS_LIST_FAILURE =
  "FETCH_ALL_NOTIFICATIONS_LIST_FAILURE";

// Quiz

//fetch all qns list by level
export const FETCH_QUESTION_LIST = "FETCH_QUESTION_LIST";
export const FETCH_QUESTION_LIST_SUCCESS = "FETCH_QUESTION_LIST_SUCCESS";
export const FETCH_QUESTION_LIST_FAILURE = "FETCH_QUESTION_LIST_FAILURE";

//fetch all level list
export const FETCH_LEVEL_LIST = "FETCH_LEVEL_LIST";
export const FETCH_LEVEL_LIST_SUCCESS = "FETCH_LEVEL_LIST_SUCCESS";
export const FETCH_LEVEL_LIST_FAILURE = "FETCH_LEVEL_LIST_FAILURE";

//fetch all level learning mode list
export const FETCH_LEVEL_LEARNING_MODE_LIST = "FETCH_LEVEL_LEARNING_MODE_LIST";
export const FETCH_LEVEL_LEARNING_MODE_LIST_SUCCESS =
  "FETCH_LEVEL_LEARNING_MODE_LIST_SUCCESS";
export const FETCH_LEVEL_LEARNING_MODE_LIST_FAILURE =
  "FETCH_LEVEL_LEARNING_MODE_LIST_FAILURE";

//add new submission
export const ADD_NEW_SUBMISSION = "ADD_NEW_SUBMISSION";
export const ADD_NEW_SUBMISSION_SUCCESS = "ADD_NEW_SUBMISSION_SUCCESS";
export const ADD_NEW_SUBMISSION_FAILURE = "ADD_NEW_SUBMISSION_FAILURE";

//update submission
export const UPDATE_CURRENT_SUBMISSION = "UPDATE_CURRENT_SUBMISSION";
export const UPDATE_CURRENT_SUBMISSION_SUCCESS =
  "UPDATE_CURRENT_SUBMISSION_SUCCESS";
export const UPDATE_CURRENT_SUBMISSION_FAILURE =
  "UPDATE_CURRENT_SUBMISSION_FAILURE";

export const FETCH_LAST_SUBMISSION_DETAILS = "FETCH_LAST_SUBMISSION_DETAILS";
export const FETCH_LAST_SUBMISSION_DETAILS_SUCCESS =
  "FETCH_LAST_SUBMISSION_DETAILS_SUCCESS";
export const FETCH_LAST_SUBMISSION_DETAILS_FAILURE =
  "FETCH_LAST_SUBMISSION_DETAILS_FAILURE";

export const UPDATE_CURRENT_SUBMISSION_USER_LEVEL_ID =
  "UPDATE_CURRENT_SUBMISSION_USER_LEVEL_ID";

//for update current questions
export const UPDATE_CURRENT_QUESTION = "UPDATE_CURRENT_QUESTION";

//for wrong question count
export const UPDATE_WRONG_QUESTION_COUNT = "UPDATE_WRONG_QUESTION_COUNT";

//add answer for questions

export const ADD_ANSWER = "ADD_ANSWER";
export const ADD_ANSWER_SUCCESS = "ADD_ANSWER_SUCCESS";
export const ADD_ANSWER_FAILURE = "ADD_ANSWER_FAILURE";

export const HANDLE_USER_ERROR = "HANDLE_USER_ERROR";

// student practice

//strategies
export const FETCH_STRATEGIES = "FETCH_STRATEGIES";
export const FETCH_STRATEGIES_SUCCESS = "FETCH_STRATEGIES_SUCCESS";
export const FETCH_STRATEGIES_FAILURE = "FETCH_STRATEGIES_FAILURE";

// start student session timer

export const START_STUDENT_SESSION_TIMER = "START_STUDENT_SESSION_TIMER";

export const STOP_STUDENT_SESSION_TIMER = "STOP_STUDENT_SESSION_TIMER";

//practice test question list

export const FETCH_PRACTICE_TEST_QUESTION_LIST =
  "FETCH_PRACTICE_TEST_QUESTION_LIST";
export const FETCH_PRACTICE_TEST_QUESTION_LIST_SUCCESS =
  "FETCH_PRACTICE_TEST_QUESTION_LIST_SUCCESS";
export const FETCH_PRACTICE_TEST_QUESTION_LIST_FAILURE =
  "FETCH_PRACTICE_TEST_QUESTION_LIST_FAILURE";

// create practice test submission
export const ADD_NEW_PRACTICE_TEST_SUBMISSION =
  "ADD_NEW_PRACTICE_TEST_SUBMISSION";
export const ADD_NEW_PRACTICE_TEST_SUBMISSION_SUCCESS =
  "ADD_NEW_PRACTICE_TEST_SUBMISSION_SUCCESS";
export const ADD_NEW_PRACTICE_TEST_SUBMISSION_FAILURE =
  "ADD_NEW_PRACTICE_TEST_SUBMISSION_FAILURE";

export const ADD_STUDENT_ORDER_PRACTICE_TEST_SUBMISSION =
  "ADD_NEW_STUDENT_PRACTICE_TEST_SUBMISSION";
export const ADD_STUDENT_ORDER_PRACTICE_TEST_SUBMISSION_SUCCESS =
  "ADD_NEW_STUDENT_PRACTICE_TEST_SUBMISSION_SUCCESS ";
export const ADD_STUDENT_ORDER_PRACTICE_TEST_SUBMISSION_FAILURE =
  "ADD_NEW_STUDENT_PRACTICE_TEST_SUBMISSION_FAILURE";

export const ADD_BATCH_PRACTICE_TEST_ANSWER_LIST =
  "ADD_BATCH_PRACTICE_TEST_ANSWER_LIST";
export const ADD_BATCH_PRACTICE_TEST_ANSWER_LIST_SUCCESS =
  "ADD_BATCH_PRACTICE_TEST_ANSWER_LIST_SUCCESS";
export const ADD_BATCH_PRACTICE_TEST_ANSWER_LIST_FAILURE =
  "ADD_BATCH_PRACTICE_TEST_ANSWER_LIST_FAILURE";

// fetch level lifter
export const FETCH_LEVEL_LIFTER_SUBMISSION_COUNT =
  "FETCH_LEVEL_LIFTER_SUBMISSION_COUNT";
export const FETCH_LEVEL_LIFTER_SUBMISSION_COUNT_SUCCESS =
  "FETCH_LEVEL_LIFTER_SUBMISSION_COUNT_SUCCESS";
export const FETCH_LEVEL_LIFTER_SUBMISSION_COUNT_FAILURE =
  "FETCH_LEVEL_LIFTER_SUBMISSION_COUNT_FAILURE";

export const FETCH_LEVEL_LIFTER_QUESTION_LIST =
  "FETCH_LEVEL_LIFTER_QUESTION_LIST";
export const FETCH_LEVEL_LIFTER_QUESTION_LIST_SUCCESS =
  "FETCH_LEVEL_LIFTER_QUESTION_LIST_SUCCESS";
export const FETCH_LEVEL_LIFTER_QUESTION_LIST_FAILURE =
  "FETCH_LEVEL_LIFTER_QUESTION_LIST_FAILURE";

export const ADD_LEVEL_LIFTER_ANSWER = "ADD_LEVEL_LIFTER_ANSWER";
export const ADD_LEVEL_LIFTER_ANSWER_SUCCESS =
  "ADD_LEVEL_LIFTER_ANSWER_SUCCESS";
export const ADD_LEVEL_LIFTER_ANSWER_FAILURE =
  "ADD_LEVEL_LIFTER_ANSWER_FAILURE";

export const ADD_NEW_LEVEL_LIFTER_TEST_SUBMISSION =
  "ADD_NEW_LEVEL_LIFTER_TEST_SUBMISSION";
export const ADD_NEW_LEVEL_LIFTER_TEST_SUBMISSION_SUCCESS =
  "ADD_NEW_LEVEL_LIFTER_TEST_SUBMISSION_SUCCESS";
export const ADD_NEW_LEVEL_LIFTER_TEST_SUBMISSION_FAILURE =
  "ADD_NEW_LEVEL_LIFTER_TEST_SUBMISSION_FAILURE";

//update submission
export const UPDATE_CURRENT_LEVEL_LIFTER_SUBMISSION =
  "UPDATE_CURRENT_LEVEL_LIFTER_SUBMISSION";
export const UPDATE_CURRENT_LEVEL_LIFTER_SUBMISSION_SUCCESS =
  "UPDATE_CURRENT_LEVEL_LIFTER_SUBMISSION_SUCCESS";
export const UPDATE_CURRENT_LEVEL_LIFTER_SUBMISSION_FAILURE =
  "UPDATE_CURRENT_LEVEL_LIFTER_SUBMISSION_FAILURE";
//CLASS

export const FETCH_ALL_CLASS_CODE_LIST = "FETCH_ALL_CLASS_CODE_LIST";
export const FETCH_ALL_CLASS_CODE_LIST_SUCCESS =
  "FETCH_ALL_CLASS_CODE_LIST_SUCCESS";
export const FETCH_ALL_CLASS_CODE_LIST_FAILURE =
  "FETCH_ALL_CLASS_CODE_LIST_FAILURE";

export const ADD_SELECTED_CLASS_CODE = "ADD_SELECTED_CLASS_CODE";
export const ADD_SELECTED_CLASS_CODE_SUCCESS =
  "ADD_SELECTED_CLASS_CODE_SUCCESS";
export const ADD_SELECTED_CLASS_CODE_FAILURE =
  "ADD_SELECTED_CLASS_CODE_FAILURE";

export const ADD_CLASS_CODE = "ADD_CLASS_CODE";
export const ADD_CLASS_CODE_SUCCESS = "ADD_CLASS_CODE_SUCCESS";
export const ADD_CLASS_CODE_FAILURE = "ADD_CLASS_CODE_FAILURE";
export const DELETE_CLASS_CODE = "DELETE_CLASS_CODE";
export const DELETE_CLASS_CODE_SUCCESS = "DELETE_CLASS_CODE_SUCCESS";
export const DELETE_CLASS_CODE_FAILURE = "DELETE_CLASS_CODE_FAILURE";
export const EDIT_CLASS_CODE = "EDIT_CLASS_CODE";
export const EDIT_CLASS_CODE_SUCCESS = "EDIT_CLASS_CODE_SUCCESS";
export const EDIT_CLASS_CODE_FAILURE = "EDIT_CLASS_CODE_FAILURE";
export const HANDLE_CLASS_CODE_ERROR = "HANDLE_CLASS_CODE_ERROR";

//GOOGLE CLASS ROOM

export const FETCH_ALL_CLASS_CODE_LIST_FROM_GOOGLE_CLASSROOM =
  "FETCH_ALL_CLASS_CODE_LIST_FROM_GOOGLE_CLASSROOM";
export const FETCH_ALL_CLASS_CODE_LIST_FROM_GOOGLE_CLASSROOM_SUCCESS =
  "FETCH_ALL_CLASS_CODE_LIST_FROM_GOOGLE_CLASSROOM_SUCCESS";
export const FETCH_ALL_CLASS_CODE_LIST_FROM_GOOGLE_CLASSROOM_FAILURE =
  "FETCH_ALL_CLASS_CODE_LIST_FROM_GOOGLE_CLASSROOM_FAILURE";

//SESSION
export const START_SESSION = "START_SESSION";
export const START_SESSION_SUCCESS = "START_SESSION_SUCCESS";
export const START_SESSION_FAILURE = "START_SESSION_FAILURE";

export const END_SESSION = "END_SESSION";
export const END_SESSION_SUCCESS = "END_SESSION_SUCCESS";
export const END_SESSION_FAILURE = "END_SESSION_FAILURE";

export const FETCH_ALL_SESSION_LIST = "FETCH_ALL_SESSION_LIST";
export const FETCH_ALL_SESSION_LIST_SUCCESS = "FETCH_ALL_SESSION_LIST_SUCCESS";
export const FETCH_ALL_SESSION_LIST_FAILURE = "FETCH_ALL_SESSION_LIST_FAILURE";

export const FETCH_WEEKLY_SESSION_LIST = "FETCH_WEEKLY_SESSION_LIST";
export const FETCH_WEEKLY_SESSION_LIST_SUCCESS =
  "FETCH_WEEKLY_SESSION_LIST_SUCCESS";
export const FETCH_WEEKLY_SESSION_LIST_FAILURE =
  "FETCH_WEEKLY_SESSION_LIST_FAILURE";

export const FETCH_MONTLY_SESSION_LIST = "FETCH_MONTLY_SESSION_LIST";
export const FETCH_MONTLY_SESSION_LIST_SUCCESS =
  "FETCH_MONTLY_SESSION_LIST_SUCCESS";
export const FETCH_MONTLY_SESSION_LIST_FAILURE =
  "FETCH_MONTLY_SESSION_LIST_FAILURE";

//strategy

export const FETCH_ALL_STRATEGY_LIST = "FETCH_ALL_STRATEGY_LIST";
export const FETCH_ALL_STRATEGY_LIST_SUCCESS =
  "FETCH_ALL_STRATEGY_LIST_SUCCESS";
export const FETCH_ALL_STRATEGY_LIST_FAILURE =
  "FETCH_ALL_STRATEGY_LIST_FAILURE";

export const UPDATE_PRACTICE_SESSION_PROGRESS_BAR_PERCENTAGE =
  "UPDATE_PRACTICE_SESSION_PROGRESS_BAR_PERCENTAGE";

//header

export const HEADER_SEARCH_TEXT = "HEADER_SEARCH_TEXT";
export const HEADER_SEARCH_CLASS_CODE = "HEADER_SEARCH_CLASS_CODE";
export const HEADER_RESET_FILTER = "HEADER_RESET_FILTER";

//student individual report
export const FETCH_STUDENT_INDIVIDUAL_REPORT =
  "FETCH_STUDENT_INDIVIDUAL_REPORT";
export const FETCH_STUDENT_INDIVIDUAL_REPORT_SUCCESS =
  "FETCH_STUDENT_INDIVIDUAL_REPORT_SUCCESS";
export const FETCH_STUDENT_INDIVIDUAL_REPORT_FAILURE =
  "FETCH_STUDENT_INDIVIDUAL_REPORT_FAILURE";

//student group report
export const FETCH_STUDENTS_GROUP_REPORT = "FETCH_STUDENTS_GROUP_REPORT";
export const FETCH_STUDENTS_GROUP_REPORT_SUCCESS =
  "FETCH_STUDENTS_GROUP_REPORT_SUCCESS";
export const FETCH_STUDENTS_GROUP_REPORT_FAILURE =
  "FETCH_STUDENTS_GROUP_REPORT_FAILURE";

//student group report
export const FETCH_GROWTH_GAUGE_REPORT = "FETCH_GROWTH_GAUGE_REPORT";
export const FETCH_GROWTH_GAUGE_REPORT_SUCCESS =
  "FETCH_GROWTH_GAUGE_REPORT_SUCCESS";
export const FETCH_GROWTH_GAUGE_REPORT_FAILURE =
  "FETCH_GROWTH_GAUGE_REPORT_FAILURE";

//CLASS LINK CLASSES
export const FETCH_CLASS_LINK_CLASSES = "FETCH_CLASS_LINK_CLASSES";
export const FETCH_CLASS_LINK_CLASSES_SUCCESS =
  "FETCH_CLASS_LINK_CLASSES_SUCCESS";
export const FETCH_CLASS_LINK_CLASSES_FAILURE =
  "FETCH_CLASS_LINK_CLASSES_FAILURE";

//CLASS LINK CLASSES students
export const ADD_SELECTED_CLASS_LINK_CLASS = "ADD_SELECTED_CLASS_LINK_CLASS";
export const ADD_SELECTED_CLASS_LINK_CLASS_SUCCESS =
  "ADD_SELECTED_CLASS_LINK_CLASS_SUCCESS";
export const ADD_SELECTED_CLASS_LINK_CLASS_FAILURE =
  "ADD_SELECTED_CLASS_LINK_CLASS_FAILURE";

//TEACHER CODE  DELETE
export const DELETE_TEACHER_CODE = "DELETE_TEACHER_CODE";
export const DELETE_TEACHER_CODE_SUCCESS = "DELETE_TEACHER_CODE_SUCCESS";
export const DELETE_TEACHER_CODE_FAILURE = " DELETE_TEACHER_CODE_FAILURE";

//EDIT TEACHER CODE
// export const EDIT_TEACHER_CODE = "EDIT_TEACHER_CODE";
// export const EDIT_TEACHER_CODE_SUCCESS = "EDIT_TEACHER_CODE_SUCCESS";
// export const EDIT_TEACHER_CODE_FAILURE = " EDIT_TEACHER_CODE_FAILURE";

// EDIT_TEACHER_CODE,
//   EDIT_TEACHER_CODE_SUCCESS,
//   EDIT_TEACHER_CODE_FAILURE,
