export const sampleDigitPlusMultiple = [
  {
    question: "7 + 1",
    question_id: 61,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 8,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-multiple",
    first_factor: 70,
    second_factor: 20,
    desc: "",
  },
  {
    question: "6 + 2",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 8,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-multiple",
    first_factor: 60,
    second_factor: 20,
    desc: "",
  },
  {
    question: "7 + 3",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 10,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-multiple",
    first_factor: 70,
    second_factor: 30,
    desc: "",
  },
  {
    question: "4 + 3",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 7,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-multiple",
    first_factor: 40,
    second_factor: 30,
    desc: "",
  },
  {
    question: "7 + 10",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 17,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-multiple",
    first_factor: 70,
    second_factor: 20,
    desc: "",
  },
  {
    question: "8 + 9",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 17,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-multiple",
    first_factor: 80,
    second_factor: 49,
    desc: "",
  },
  {
    question: "5 + 8",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 13,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-multiple",
    first_factor: 50,
    second_factor: 38,
    desc: "",
  },
];

export const sampleDigitMinusMultiple = [
  {
    question: "7 + 1",
    question_id: 61,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 8,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-multiple",
    second_factor: 40,
    first_factor: 85,
    desc: "",
  },
  {
    question: "6 + 2",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 8,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-multiple",
    second_factor: 30,
    first_factor: 55,
    desc: "",
  },
  {
    question: "7 + 3",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 10,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-multiple",
    second_factor: 50,
    first_factor: 66,
    desc: "",
  },
  {
    question: "4 + 3",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 7,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-multiple",
    second_factor: 30,
    first_factor: 77,
    desc: "",
  },
  {
    question: "7 + 10",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 17,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-multiple",
    second_factor: 20,
    first_factor: 44,
    desc: "",
  },
  {
    question: "8 + 9",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 17,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-multiple",
    second_factor: 30,
    first_factor: 67,
    desc: "",
  },
  {
    question: "5 + 8",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 13,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-multiple",
    second_factor: 50,
    first_factor: 97,
    desc: "",
  },
];

export const sampleDigitPlusTwoDigits = [
  {
    question: "7 + 1",
    question_id: 61,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 8,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit",
    first_factor: 48,
    second_factor: 23,
    desc: "",
  },
  {
    question: "6 + 2",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 8,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit",
    first_factor: 55,
    second_factor: 27,
    desc: "",
  },
  {
    question: "7 + 3",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 10,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit",
    first_factor: 28,
    second_factor: 42,
    desc: "",
  },
  {
    question: "4 + 3",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 7,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit",
    first_factor: 58,
    second_factor: 28,
    desc: "",
  },
  {
    question: "7 + 10",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 17,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit",
    first_factor: 39,
    second_factor: 52,
    desc: "",
  },
  {
    question: "8 + 9",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 17,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit",
    first_factor: 16,
    second_factor: 35,
    desc: "",
  },
  {
    question: "5 + 8",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 13,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit",
    first_factor: 51,
    second_factor: 44,
    desc: "",
  },
  {
    question: "7 + 1",
    question_id: 61,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 8,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit",
    first_factor: 48,
    second_factor: 82,
    desc: "",
  },
  {
    question: "6 + 2",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 8,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit",
    first_factor: 55,
    second_factor: 77,
    desc: "",
  },
  {
    question: "7 + 3",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 10,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit",
    first_factor: 28,
    second_factor: 92,
    desc: "",
  },
  {
    question: "4 + 3",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 7,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit",
    first_factor: 58,
    second_factor: 78,
    desc: "",
  },
  {
    question: "7 + 10",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 17,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit",
    first_factor: 39,
    second_factor: 82,
    desc: "",
  },
  {
    question: "8 + 9",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 17,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit",
    first_factor: 16,
    second_factor: 85,
    desc: "",
  },
  {
    question: "5 + 8",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 13,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit",
    first_factor: 51,
    second_factor: 54,
    desc: "",
  },
];

export const sampleDigitMinusTwoDigits = [
  {
    question: "7 + 1",
    question_id: 61,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 8,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-2-digit",
    second_factor: 45,
    first_factor: 85,
    desc: "",
  },
  {
    question: "6 + 2",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 8,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-2-digit",
    second_factor: 30,
    first_factor: 55,
    desc: "",
  },
  {
    question: "7 + 3",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 10,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-2-digit",
    second_factor: 50,
    first_factor: 66,
    desc: "",
  },
  {
    question: "4 + 3",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 7,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-2-digit",
    second_factor: 30,
    first_factor: 77,
    desc: "",
  },
  {
    question: "7 + 10",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 17,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-2-digit",
    second_factor: 20,
    first_factor: 44,
    desc: "",
  },
  {
    question: "8 + 9",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 17,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-2-digit",
    second_factor: 30,
    first_factor: 67,
    desc: "",
  },
  {
    question: "5 + 8",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 13,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-2-digit",
    second_factor: 50,
    first_factor: 97,
    desc: "",
  },
];

export const sampleDigitPlusTwoDigitsOfNine = [
  {
    question: "7 + 1",
    question_id: 61,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 8,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit-of-nine",
    first_factor: 48,
    second_factor: 29,
    desc: "",
  },
  {
    question: "6 + 2",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 8,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit-of-nine",
    first_factor: 55,
    second_factor: 29,
    desc: "",
  },
  {
    question: "7 + 3",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 10,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit-of-nine",
    first_factor: 28,
    second_factor: 49,
    desc: "",
  },
  {
    question: "4 + 3",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 7,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit-of-nine",
    first_factor: 58,
    second_factor: 29,
    desc: "",
  },
  {
    question: "7 + 10",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 17,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit-of-nine",
    first_factor: 39,
    second_factor: 59,
    desc: "",
  },
  {
    question: "8 + 9",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 17,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit-of-nine",
    first_factor: 16,
    second_factor: 39,
    desc: "",
  },
  {
    question: "5 + 8",
    question_id: 62,
    math_operation_id: 1,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 13,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-plus-2-digit-of-nine",
    first_factor: 51,
    second_factor: 49,
    desc: "",
  },
];
export const sampleDigitMinusTwoDigitsOfNine = [
  {
    question: "7 + 1",
    question_id: 61,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 8,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-2-digit-of-nine",
    second_factor: 49,
    first_factor: 85,
    desc: "",
  },
  {
    question: "6 + 2",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 8,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-2-digit-of-nine",
    second_factor: 39,
    first_factor: 55,
    desc: "",
  },
  {
    question: "7 + 3",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 10,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-2-digit-of-nine",
    second_factor: 59,
    first_factor: 66,
    desc: "",
  },
  {
    question: "4 + 3",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 7,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-2-digit-of-nine",
    second_factor: 39,
    first_factor: 77,
    desc: "",
  },
  {
    question: "7 + 10",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 17,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-2-digit-of-nine",
    second_factor: 29,
    first_factor: 44,
    desc: "",
  },
  {
    question: "8 + 9",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 17,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-2-digit-of-nine",
    second_factor: 39,
    first_factor: 67,
    desc: "",
  },
  {
    question: "5 + 8",
    question_id: 62,
    math_operation_id: 2,
    level_id: 19,
    level_title: "Level L (x7)",
    correct_answer: 13,
    is_correct: 0,
    retry_count: 0,
    time_taken_in_second: 0,
    hint_count: 1,
    slug: "2-digit-minus-2-digit-of-nine",
    second_factor: 59,
    first_factor: 97,
    desc: "",
  },
];
